name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  dotnet_sdk_version: '8.0.x'
  postgis_version: 3
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Windows comes with PG pre-installed, and defines the PGPASSWORD environment variable. Remove it as it interferes
  # with some of our tests
  PGPASSWORD: ""

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            ${{ env.dotnet_sdk_version }}

      - name: Build
        run: dotnet build -c Release /p:LanguageVersion=latest
        shell: bash
