name: Publish

on:
  push:
    branches:
      - billee-main

env:
  dotnet_sdk_version: '8.0.x'

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}

      - name: Pack
        run: dotnet pack Npgsql.sln --configuration Release --output ${{ github.workspace }}/packages

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}"
          dotnet nuget push ${{ github.workspace }}/packages/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}
